[package]
name = "fastmc"
version = "0.3.0"
description = "set up a Minecraft server in under a minute"
license = "Apache-2.0"
edition = "2024"

[dependencies]
colored = "3"
chrono = "0.4"
rand = "0.8"
regex = "1"
shellexpand = "3"
anyhow = "1.0"
libc = "0.2"
dirs = "5"
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde_json = "1"

[profile.release]
opt-level       = 3
lto             = "fat"
codegen-units   = 1
panic           = "abort"
strip           = "symbols"
